### ISSUE TITLE
PSA: Upcoming large code updates in Core

### ISSUE THREAD

**Issue by nytamin** [nrkno/tv-automation-server-core#159]
This is a PSA about a fairly large upcoming code-change that are planned for Core.

**Code formatting**
PR: #146 
We will start using Prettier as code formatter for the project.

This will result in a lot of code that will be changed (formatted differently), which might affect how easy it is to make PR:s and commits from external repos.
It is therefore recommended that any contributions made by external contributors be presented at the latest **2020-02-10**.
The Code formatting will be applied ~~2020-02-18~~, so expect to have to rebase any changes done after that.

Note: The formatting have not been applied yet, we're wrapping some things internally and hope to get around to it asap.

**Comment by Julusian** [comment]
https://github.com/nrkno/tv-automation-server-core/issues/240
