### ISSUE TITLE
UI Timeline bug: overlapping time labels

### ISSUE THREAD

**Issue by jesperstarkar** [nrkno/tv-automation-server-core#2]
![screen shot 2018-04-10 at 22 09 19](https://user-images.githubusercontent.com/6236874/38581098-179d8772-3d0c-11e8-9cea-8a86f6bf9c11.png)

Happened after the first "scramble time" debug function.

**Comment by jstarpl** [comment]
This should now be resolved, since the scale for the display is dynamic.
