### ISSUE TITLE
PSA: The large reformat

### ISSUE THREAD

**Issue by Julusian** [nrkno/tv-automation-server-core#240]
As we planned to do many months ago, this repository has now been reformatted using prettier.
This can cause large and painful merge conflicts in pull requests unless handled carefully. This issue aims to outline advice and steps to mitigate any pain that may be felt because of this.

### Process for a painless merge
The best process for handling this, is to merge the formatted branch into yours.

1) Firstly, you need to identify the 2 important commits from the branch you want to merge in. These are the commit just before the merge, and the commit of the merge. To identify these, look in the git history for the merge commit adding the            prettier config, and a merge commit soon after which applies this formatting. Github does not make the correct commits very clear, some desktop tools show it a lot better.
For the release21 branch, these are 4864ff53 and 6314c740.
For the master branch, these are d7a403c6 and 16cf61da.
**Note**: the remaining steps will assume you are working with master, and will use the commit ids as shown above

1) checkout your branch to update
1) Pull in any changes `git merge d7a403c6`
    **IMPORTANT**: any merge conflicts need to be committed with `git commit --no-verify` to avoid premature formatting of the changes
1) If you are on windows, you will need to cherry-pick in https://github.com/nrkno/tv-automation-server-core/commit/761f9278b35d80f5104b4728bb5830621d5e8487 and https://github.com/nrkno/tv-automation-server-core/commit/d36db2a89f68e11ae5edca85e6355ac794fd65c9 to get the scripts to work properly
1) Pull in the format change `git merge 16cf61da`
1) Discard any changes, and delete any 'new' files
1) `meteor npm run quickformat`
1) `meteor npm run lint -- --fix`
    **Note**: Ensure no errors are reported by this. any which are need to be fixed before continuing
1) Commit all changed files. This should be done as a normal commit again, and will verify the lint is ok
1) Pull in any newer changes `git merge master`

**Comment by jstarpl** [comment]
There seems to be some problems developing on Windows now, after the Husky change:
1) `meteor npm run quickformat` works only on Unix-based systems (the command syntax used in the script is Unix-specific)
2) the `husky` may work only on Unix-based systems (the way filenames are piped to the linter may cause an "ENAMETOOLONG" exception, if the number of staged files is significant), there is a suggestion to look up: https://github.com/okonet/lint-staged#using-js-functions-to-customize-tasks which suggest just running the commands on an entire repository if the resulted argument list is expected to be too long (https://github.com/okonet/lint-staged#example-run-eslint-on-entire-repo-if-more-than-10-staged-files)

**Comment by Julusian** [comment]
1) Oops, hopefully an easy fix? That is intended to be a temporary command, so feel free to make even more of a mess of it, or perhaps duplicate and make a windows specific version
2) I did digging, and it appears to have been fixed in husky v10 (which requires node 10) https://github.com/okonet/lint-staged/pull/732 https://github.com/okonet/lint-staged/issues/147. But was also supported for a period up until v9, so the quick fix might be to downgrade husky to v8.2.1 until we get meteor 1.10

**Comment by jstarpl** [comment]
I think I was able to fix both issues here: https://github.com/nrkno/tv-automation-server-core/pull/242
