### ISSUE TITLE
Four styles for each layer item label

### ISSUE THREAD

**Issue by hummelstrand** [nrkno/tv-automation-server-core#3]
If you set up four levels of font styles, I'll add the styling.

- Bold
- Regular
- Light
- Light, File Missing

**Comment by jstarpl** [comment]
I've addded four styles: `bold`, `regular`, `light` and `light-file-missing` - for the time being, they can be switched using Ctrl/Cmd+Click on a timeline item. There's some placeholder styling in runningOrderView also.
