### ISSUE TITLE
Push LICENSE file to master to set GitHub license tracking correctly for the repo

### ISSUE THREAD

**Issue by hummelstrand** [nrkno/tv-automation-server-core#4]

**Comment by jstarpl** [comment]
Our LICENSE modification turned out to be too complicated for GitHub to see as a MIT license. I've moved the trademark comment to ReadMe, as per GitHub recommendation in these kinds of situations.

**Comment by baltedewit** [comment]
https://github.com/nrkno/core-icons/blob/master/lib/nrk-logo-nrk-1.svg

Does that mean they already put it under MIT themselves? There seems to be no copyright/trademark in that repo. Or might they not be aware of this?

**Comment by jesperstarkar** [comment]
I'm thinking the latter.
