### ISSUE TITLE
Probel With blueprint mismatch

### ISSUE THREAD

**Issue by rakibhossensweet** [nrkno/tv-automation-server-core#502]
I am new to the Sofie core system. 
I follow the  Documentation "https://sofie.gitbook.io/sofie-tv-automation/documentation" But every time I got the following error. Kindly anyone help me. 
**Where I put the credential for google spreedsheet. I don't find it in UI ?**
**How can I update the Sofie core.** 
**How can I resolve the following issue**

There are no rundowns ingested into Sofie.

Sofie Automation version: 1.17.0

System Status: FAIL / BAD
Status Messages:
check blueprintCompability_kxu7tyKGeaL78K5SL: Integration version: Version mismatch: blueprint.integrationVersion version: "0.24.1" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)
check blueprintCompability_s87zxttpnnecZARhm: Integration version: Version mismatch: blueprint.integrationVersion version: "0.24.1" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)
check blueprintCompability_RWzdovMd8gPJrCXTT: Integration version: Version mismatch: blueprint.integrationVersion version: "0.24.1" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)
device0 (CasparCG device0 192.168.100.2:5250): CasparCG disconnected
Spreadsheet Gateway: Not set up: Credentials missing

**Comment by nytamin** [comment]
Sorry for not replying to this earlier, we must've missed the notification for this one.

Did you figure it out on your self? If not, I recommend that you post your question in the [Sofie Slack](https://join.slack.com/t/sofietv/shared_invite/enQtNTk2Mzc3MTQ1NzAzLTJkZjMyMDg3OGM0YWU3MmU4YzBhZDAyZWI1YmJmNmRiYWQ1OTZjYTkzOTkzMTA2YTE1YjgxMmVkM2U1OGZlNWI)
