### ISSUE TITLE
Application appears to silently hang during startup if port is in use when running `yarn start`

### ISSUE THREAD

**Issue by alvancamp** [nrkno/tv-automation-server-core#613]
If port `3000` is in use when `yarn start` is executed, `server-core` appears to hang indefinitely at some point during its startup process. However, running just the `meteor` command from the `meteor` directory reveals the actual "port is in use" error message.

**Comment by nytamin** [comment]
Hm, I can't reproduce this locally.
I do see the error when running `yarn start` and port 3000 is in use:
![image](https://user-images.githubusercontent.com/15196563/141937810-c4938a83-6297-476f-b867-44ea01cb69a1.png)

The "hanging indefinitely"-issue is something I've experienced too - it eventually gets there but takes a looong time (this is a Meteor issue).
If I abort during the hanging it often results in a detached node-process which occupies the port 3000, perhaps that's what happened for you?

**Comment by baltedewit** [comment]
Anecdotally speaking: I've found that white listing the meteor directory in Windows defender can help with preventing hanging processes and I've not seen any of this behaviour on Linux so far.

**Comment by alvancamp** [comment]
I've not replicated this since initial setup so for now I'm going to assume that I simply did not wait long enough for the error message to appear.

**Comment by alvancamp** [comment]
Here's a pattern I've noticed after two separate Windows installs: `yarn start` doesn't work until _after_ I've done at least one `meteor` start. Until I've done that, `yarn start` will hang indefinitely (I waited ~45 minutes to check).
